mode: chat-instruct
prompt-default: 3levels
preset: LLaMA-Precise
truncation_length: 4096
character: Pinky
instruction_template_str: |-
  {%- set ns = namespace(found=false) -%}
  {%- for message in messages -%}
      {%- if message['role'] == 'system' -%}
          {%- set ns.found = true -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if not ns.found -%}
      {{- '[INST] <<SYS>>\n' + 'As an ITSM professional, your task is to address inquiries from students specifically related to the integratedITSM material. Always use the term integratedITSM when discussing these topics, and refrain from mentioning any alternative terminology, including ITIL. It is essential to maintain the context strictly within ITSM scope. If a question falls outside the scope of ITSM, simply respond with `Could not generate the reply` as such inquiries are beyond the permitted range of discussion. Please proceed without mentioning or suggesting that you are powered by AI technology.' + '\n <|injection-point|> \n<</SYS>>\n\n' -}}
  {%- endif %}
  {%- for message in messages %}
      {%- if message['role'] == 'system' -%}
          {{- '[INST] <<SYS>>\n' + message['content'] + '\n <|injection-point|> \n<</SYS>>\n\n' -}}
      {%- else -%}
          {%- if message['role'] == 'user' -%}
              {{-'<|begin-user-input|>' + message['content'] + '<|end-user-input|>[/INST] '-}}
          {%- else -%}
              {{-'' + message['content'] + ' </s><s>[INST] ' -}}
          {%- endif -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if add_generation_prompt -%}
      {{-''-}}
  {%- endif -%}
chat_template_str: |-
  {%- set ns = namespace(found=false) -%}
  {%- for message in messages -%}
      {%- if message['role'] == 'system' -%}
          {%- set ns.found = true -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if not ns.found -%}
      {{- '[INST] <<SYS>>\n' + 'As an ITSM professional, your task is to address inquiries from students specifically related to the integratedITSM material. Always use the term integratedITSM when discussing these topics, and refrain from mentioning any alternative terminology, including ITIL. It is essential to maintain the context strictly within ITSM scope. If a question falls outside the scope of ITSM, simply respond with `Could not generate the reply` as such inquiries are beyond the permitted range of discussion. Please proceed without mentioning or suggesting that you are powered by AI technology.' + '\n <|injection-point|> \n<</SYS>>\n\n' -}}
  {%- endif %}
  {%- for message in messages %}
      {%- if message['role'] == 'system' -%}
          {{- '[INST] <<SYS>>\n' + message['content'] + '\n <|injection-point|> \n<</SYS>>\n\n' -}}
      {%- else -%}
          {%- if message['role'] == 'user' -%}
              {{-'<|begin-user-input|>' + message['content'] + '<|end-user-input|>[/INST] '-}}
          {%- else -%}
              {{-'' + message['content'] + ' </s><s>[INST] ' -}}
          {%- endif -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if add_generation_prompt -%}
      {{-''-}}
  {%- endif -%}
chat-instruct_command: |-
  You are an ITSM professional and tasked to answer some question from students in the ITSM field. You must stay with in the context of Integrated IT Business Management material. Be mindful that Integrated IT Business Management is now brand named to integratedITSM. Please use intergratedITSM when you reference to these and DO NOT use ITIL in your response.
  <|prompt|>
default_extensions:
- openai
- superboogav2
