meta-llama_Llama-2-13b-chat-hf$:
  loader: Transformers
  cpu_memory: 0
  auto_devices: true
  disk: false
  cpu: false
  bf16: false
  load_in_8bit: false
  trust_remote_code: false
  no_use_fast: false
  use_flash_attention_2: false
  load_in_4bit: true
  compute_dtype: float16
  quant_type: nf4
  use_double_quant: true
  disable_exllama: false
  disable_exllamav2: false
  compress_pos_emb: 1
  alpha_value: 1
  rope_freq_base: 0
  gpu_memory_0: 0
  instruction_template: ITSM-LLAMA-RAG
meta-llama_Llama-2-70b-chat-hf$:
  loader: Transformers
  cpu_memory: 0
  auto_devices: true
  disk: false
  cpu: false
  bf16: false
  load_in_8bit: false
  trust_remote_code: false
  no_use_fast: false
  use_flash_attention_2: false
  load_in_4bit: true
  compute_dtype: float16
  quant_type: nf4
  use_double_quant: true
  disable_exllama: false
  disable_exllamav2: false
  compress_pos_emb: 1
  alpha_value: 1
  rope_freq_base: 0
  gpu_memory_0: 0
  instruction_template: ITSM-LLAMA-RAG

